# This is for the dronie 1.0 agent
# https://docs.drone.io/user-guide/pipeline/steps/ https://docs.drone.io/user-guide/pipeline/migrating/
# See https://git.osgeo.org/gogs/geos/geos-docker
test-image: &test-image docker.kbt.io/geos/build-test:alpine

kind: pipeline
name: default

clone:
    image: plugins/git
    depth: 50
    recursive: false

steps:
  - name: build
    image: *test-image
    pull: true
    commands:
      - ./autogen.sh
      - CXXFLAGS="-O0" ./configure
      - make V=0
  - name: check
    image: *test-image
    commands:
      - CXXFLAGS="-O0" make check V=0
  - name: docs
    image: *test-image
    commands:
      - make doxygen 2> doxygen.err
      - ! grep -v '\(not documented\|ignoring unsupported taz\)' doxygen.err
